<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#15.1-NumPy简介" data-toc-modified-id="15.1-NumPy简介-1">15.1 NumPy 简介</a></span></li><li><span><a href="#15.2-NumPy数组的生成" data-toc-modified-id="15.2-NumPy数组的生成-2">15.2 NumPy 数组的生成</a></span><ul class="toc-item"><li><span><a href="#15.2.1-生成一般数组" data-toc-modified-id="15.2.1-生成一般数组-2.1">15.2.1 生成一般数组</a></span></li><li><span><a href="#15.2.2-生成特殊类型数组" data-toc-modified-id="15.2.2-生成特殊类型数组-2.2">15.2.2 生成特殊类型数组</a></span></li><li><span><a href="#15.2.3-生成随机数组" data-toc-modified-id="15.2.3-生成随机数组-2.3">15.2.3 生成随机数组</a></span><ul class="toc-item"><li><span><a href="#np.random.rand()方法" data-toc-modified-id="np.random.rand()方法-2.3.1"><strong><code>np.random.rand()</code> 方法 </strong></a></span></li><li><span><a href="#np.random.randn()方法" data-toc-modified-id="np.random.randn()方法-2.3.2"><strong><code>np.random.randn()</code> 方法 </strong></a></span></li><li><span><a href="#np.random.randint()方法" data-toc-modified-id="np.random.randint()方法-2.3.3"><strong>np.random.randint () 方法 </strong></a></span></li><li><span><a href="#np.random.choice()方法" data-toc-modified-id="np.random.choice()方法-2.3.4"><strong><code>np.random.choice()</code> 方法 </strong></a></span></li><li><span><a href="#np.random.shuffle()方法" data-toc-modified-id="np.random.shuffle()方法-2.3.5"><strong><code>np.random.shuffle()</code> 方法 </strong></a></span></li></ul></li></ul></li><li><span><a href="#15.3-NumPy数组的基本属性" data-toc-modified-id="15.3-NumPy数组的基本属性-3">15.3 NumPy 数组的基本属性</a></span><ul class="toc-item"><li><span><a href="#数组的形状" data-toc-modified-id="数组的形状-3.1"><strong>数组的形状 </strong></a></span></li><li><span><a href="#数组的大小" data-toc-modified-id="数组的大小-3.2"><strong>数组的大小 </strong></a></span></li><li><span><a href="#数组的类型" data-toc-modified-id="数组的类型-3.3"><strong>数组的类型 </strong></a></span></li><li><span><a href="#数组的维数" data-toc-modified-id="数组的维数-3.4"><strong>数组的维数 </strong></a></span></li></ul></li><li><span><a href="#15.4-NumPy数组的数据选取" data-toc-modified-id="15.4-NumPy数组的数据选取-4">15.4 NumPy 数组的数据选取</a></span><ul class="toc-item"><li><span><a href="#15.4.1-一维数据选取" data-toc-modified-id="15.4.1-一维数据选取-4.1">15.4.1 一维数据选取</a></span></li><li><span><a href="#15.4.2-多维数据选取" data-toc-modified-id="15.4.2-多维数据选取-4.2">15.4.2 多维数据选取</a></span></li></ul></li><li><span><a href="#15.5-NumPy数组的数据预处理" data-toc-modified-id="15.5-NumPy数组的数据预处理-5">15.5 NumPy 数组的数据预处理</a></span><ul class="toc-item"><li><span><a href="#15.5.1-NumPy数组的类型转换" data-toc-modified-id="15.5.1-NumPy数组的类型转换-5.1">15.5.1 NumPy 数组的类型转换</a></span></li><li><span><a href="#15.5.2-NumPy数组的缺失值处理" data-toc-modified-id="15.5.2-NumPy数组的缺失值处理-5.2">15.5.2 NumPy 数组的缺失值处理</a></span></li><li><span><a href="#15.5.3-NumPy数组的重复值处理" data-toc-modified-id="15.5.3-NumPy数组的重复值处理-5.3">15.5.3 NumPy 数组的重复值处理</a></span></li></ul></li><li><span><a href="#15.6-NumPy数组重塑" data-toc-modified-id="15.6-NumPy数组重塑-6">15.6 NumPy 数组重塑</a></span><ul class="toc-item"><li><span><a href="#15.6.1-一维数组重塑" data-toc-modified-id="15.6.1-一维数组重塑-6.1">15.6.1 一维数组重塑</a></span></li><li><span><a href="#15.6.2-多维数组重塑" data-toc-modified-id="15.6.2-多维数组重塑-6.2">15.6.2 多维数组重塑</a></span></li><li><span><a href="#15.6.3-数组转置" data-toc-modified-id="15.6.3-数组转置-6.3">15.6.3 数组转置</a></span></li></ul></li><li><span><a href="#15.7-NumPy数组合并" data-toc-modified-id="15.7-NumPy数组合并-7">15.7 NumPy 数组合并</a></span><ul class="toc-item"><li><span><a href="#15.7.1-横向合并" data-toc-modified-id="15.7.1-横向合并-7.1">15.7.1 横向合并</a></span></li><li><span><a href="#15.7.2-纵向合并" data-toc-modified-id="15.7.2-纵向合并-7.2">15.7.2 纵向合并</a></span></li></ul></li><li><span><a href="#15.8-常用数据分析函数" data-toc-modified-id="15.8-常用数据分析函数-8">15.8 常用数据分析函数</a></span><ul class="toc-item"><li><span><a href="#15.8.1-元素级函数" data-toc-modified-id="15.8.1-元素级函数-8.1">15.8.1 元素级函数</a></span></li><li><span><a href="#15.8.2-描述统计函数" data-toc-modified-id="15.8.2-描述统计函数-8.2">15.8.2 描述统计函数</a></span></li><li><span><a href="#15.8.3-条件函数" data-toc-modified-id="15.8.3-条件函数-8.3">15.8.3 条件函数</a></span></li><li><span><a href="#15.8.4-集合关系" data-toc-modified-id="15.8.4-集合关系-8.4">15.8.4 集合关系</a></span></li></ul></li></ul></div>

# 15-NumPy数组

Pandas和NumPy有一定历史渊源。Python最开始被开发出来后，人们应用时有数值计算的需求，不过当时的数值主要指矩阵相关的运算，
为了满足这种需求，NumPy问世了。

但是，在实际工作中，我们的很多数据都不是以矩阵的形式存放的，而是用数据库或者本地的Excel表格存放的。为了让人们使用更加方便，所以前辈们就在已有的NumPy的基础上开发出了Pandas。

其实这两个包所提供的计算函数差不多，你会看到这两个包在实现同一功能时用的函数都是一样的，例如，求和用的都是 `sum()`函数。我们在数据分析领域用的最多的还是Pandas，所以前面关于数据分析流程中涉及的操作都借助了Pandas包来实现。

但是Pandas是建立在NumPy基础上的，本章介绍一下NumPy中比较常用的操作。

## 15.1 NumPy简介

NumPy 是针对多维数组（Ndarray）的一个科学计算（就是各种运算）包，**这个包封装了多个可以用于数组间计算的函数供你直接调用**。

## 15.2 NumPy数组的生成

要使用NumPy，首先要有符合NumPy数组的数据，不同的包需要的数据结构不一样，比如Pandas包需要的是`DataFrame`和`Series`数据结构。

下面介绍几种生成数组的方法，在Python中创建数组使用的是`array()`函数，`array()`函数的参数可以是任何序列类型的对象（列表、元组、字符串等）。

在使用NumPy数组的函数或方法之前，首先要将这个包加载进来
```python
import numpy as np
```
在一段程序中只需加载导入进来一次即可，下面涉及NumPy中的方法，我们都假设NumPy已加载完成。

### 15.2.1 生成一般数组

给`array()`函数传入一个列表，直接将数据以列表的形式作为一个参数传给`array()`函数即可。

In [1]:
import numpy as np

In [2]:
arr = np.array([2, 4, 6, 8])
arr

array([2, 4, 6, 8])

给`array()`函数传入一个元组，直接将数据以元组的形式作为一个参数传给`array()`函数即可:

In [3]:
arr = np.array((2, 4, 6, 8))
arr

array([2, 4, 6, 8])

给`array()`函数传入一个嵌套列表，直接将数据以嵌套列表的形式作为一个参数传给`array()`函数，这个时候会生成一个多维数组

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 15.2.2 生成特殊类型数组

生成固定范围的随机数组.

生成固定范围的随机数组要用到`arange()`函数:
```python
np.arange(start,stop,step)
```
上面的代码表示生成一个以start开始(包括start这个值)，stop结束(不包括stop这个值)，step为步长的随机序列，具体例子如下：

In [5]:
np.arange(1,15,4)

array([ 1,  5,  9, 13])

当step参数省略时，步长默认为1：

In [6]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

当start参数默认不写时，默认从0开始：

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**生成指定形状全为0的数组**

生成指定形状全为0的数组要用到`zeros()`函数.

当给`zeros()`函数传入一个具体的值时，会生成相应长度的一个全为0的一维数组:

In [8]:
np.zeros(3)

array([0., 0., 0.])

当给`zeros()`函数传入一对值时，会生成相应行、列数的全为0的多维数组

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**生成指定形状全为1的数组**

生成指定形状全为1的数组，需要用到`ones()`函数。

生成全为1的数组和生成全为0的数组的思路是一致的，只不过把全为0的数组中的0全部换成1。

当给`ones()`函数传入一个具体值时，生成相应长度的一个全为 1的一维数组:

In [11]:
np.ones(3)

array([1., 1., 1.])

当给`ones()`函数传入一对值时，会生成相应行列数全为1的多维数组

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**生成一个正方形单位矩阵**

单位矩阵就是对角线的元素值全为1，其余位置的元素值全为0，需要用到`eye()`函数。

`eye()`函数需要在括号中指明正方形边长:

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 15.2.3 生成随机数组

随机数组的生成主要用到NumPy中的random模块。

#### **`np.random.rand()`方法**

`np.random.rand()`方法主要用于生成(0,1)之间的随机数组。

当给 `rand()`函数传入一个具体值时，生成一个相应长度的且值位于(0,1)之间的随机数组:

In [14]:
# 生成长度为3的位于(0,1)之间的随机数组
np.random.rand(3)

array([0.20827589, 0.46743867, 0.52542203])

当给 `rand()`函数传入一对值时，生成相应行、列数的多维数组，且数组中的值介于(0,1)之间:

In [16]:
# 生成2行3列值位于(0,1)之间的数组
np.random.rand(2,3)

array([[0.32383833, 0.90418817, 0.09956549],
       [0.26794389, 0.25122079, 0.75221553]])

#### **`np.random.randn()`方法**

`np.random.randn()`方法用来生成满足正态分布的指定形状数组.

当给`randn()`函数传入一个具体值时，生成一个相应长度的满足正态分布的随机数组:

In [17]:
# 生成长度为3的满足正态分布的随机数组
np.random.randn(3)

array([ 0.45573342, -1.19062409, -1.12361107])

当给`randn()`函数传入一对值时，生成相应行、列数的多维数组，且数组中的值满足正太分布:

In [18]:
# 生成2行3列满足正态分布的随机数组
np.random.randn(2,3)

array([[-1.05784232,  0.63864972, -1.27120968],
       [ 0.07501423, -0.9497394 , -1.00119118]])

#### **np.random.randint()方法**

`np.random.randint()`方法与`np.arange()`方法类似，用于生成一定范围内的随机数组。
```python
np.random.randint(low,high=None,size=None)
```
上面的代码表示在左闭右开区间[low,high）生成数组大小为size的均匀分布的整数值：

In [19]:
# 在区间[1，5)生成长度为10的随机数组
np.random.randint(1,5,10)

array([2, 1, 3, 2, 4, 3, 1, 2, 3, 2])

参数size可以是一个值，这个时候生成的随机数组是一维的，参数size也可以是一对值，这个时候生成的随机数组就是多维的了

In [27]:
# 在区间[0，5）上生成2行3列的随机数组
np.random.randint(5,size = (2,3))

array([[2, 1, 1],
       [0, 4, 3]])

#### **`np.random.choice()`方法**

`np.random.choice()`方法主要用来从已知数组中随机选取相应大小的数组。
```python
np.random.choice(a,size = None,replace = None,p = None)
```
上面的代码表示从数组a中选取size大小的数组作为一个新的数组，a可以是一个数组，也可以是一个整数，当a是一个数组时表示从该数组随机采样;当a为整数时，表示从range(a)中采样

In [28]:
# 从数组a中选取3个值组成一个新的数组
np.random.choice(5,3)

array([1, 4, 3])

当size是一个具体数值时，生成一维数组；当size是一对值时，生成一个指定行列的多维数组:

In [29]:
# 从数组a中选取2行3列的数值组成一个新的数组
np.random.choice(5,(2,3))

array([[3, 4, 3],
       [3, 3, 3]])

#### **`np.random.shuffle()`方法**

`np.random.shuffle()`方法主要是用来将原数组顺序打乱，类似于打扑克牌中的洗牌操作。

In [30]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.random.shuffle(arr)
arr

array([5, 7, 6, 1, 9, 8, 4, 2, 3, 0])

## 15.3 NumPy数组的基本属性

NumPy数组的基本属性主要包括数组的形状、大小、类型和维数。

### **数组的形状**

数组的形状就是指这个数组中有几行几列数据，直接调用数组的`shape`方法就可以看到，如下：

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

### **数组的大小**

数组的大小是指这个数组中总共有多少个元素，直接调用数组的`size`方法就可以看到

In [36]:
arr.size

9

### **数组的类型**


数组的类型指构成这个数组的元素都是什么类型，在NumPy中主要有5种数据类型:
```text
类型                   说明
-------------------------------------------------
int                   整型数，即整数
float                 浮点数，即含有小数点
object                Python对象类型
string                字符串类型，经常用S表示，S10表示长度为10的字符串
unicode               固定长度的unicode类型，跟字符串定义方式一样，经常用U表示
```
我们要想知道某个数组具体是什么数据类型，调用数组的`dtype`方法可以看到

In [38]:
# arr数组的类型为int
arr.dtype

dtype('int32')

### **数组的维数**

数组的维数就是指数组是几维空间的，几维空间就对应数组是几维数组，调用数组的`ndim`方法就可以看到

In [39]:
# arr数组为2维数组
arr.ndim

2

## 15.4 NumPy数组的数据选取

数据选取就是通过索引的方式把想要的某些值从全部数据中抽取出来。

### 15.4.1 一维数据选取 

**一维数据选取，一维可以理解成数据就是一行或者一列数据**，想象一下当我们要从一行或者一列数据中选取想要的某些值时我们会怎么选。
<br>先新建一个一维数组供使用：

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**传入某个位置**<br>
NumPy中的位置同样是从0开始计数的。获取第4位的数如下所示

In [41]:
# 获取第4位的数，即传入3
arr[3]

3

我们想要获取末尾的数值时，可以直接给数组传入-1，表示获取末尾最后一个数值；当给数组传入-2时，表示获取末尾第二个值。也就是数组正序从0开始数，倒序从-1开始数。

In [42]:
# 获取末尾最后一个数值
arr[-1]

9

In [43]:
# 获取末尾倒数第二个数值
arr[-2]

8

**传入某个位置区间**<br>
数组中每个元素都有一个位置，如果想要获取某些连续位置的元素，则可以将这些元素对应的位置表示成一个区间，只要写明元素开始的位置和结束的位置即可。注意，**位置默认是一个左闭右开区间**，即选取开始位置的元素，但不选取结束位置的元素。

In [44]:
# 获取位置3到5的值，不包含位置5的值
arr[3:5]

array([3, 4])

当你想要选取某个位置之后的所有元素，只要指明开始位置即可

In [45]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

也可以获取某个位置之前的所有元素，只需指明结束位置即可

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

正序位置和倒序位置还可以混用

In [47]:
arr[3:-2]

array([3, 4, 5, 6, 7])

**传入某个条件**

给数组传入某个判断条件，将返回符合该条件的元素。

In [48]:
# 获取数组中大于3的元素
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

### 15.4.2 多维数据选取

多维数据就是指这个数组是多维数组，有多行多列，思考一下要从多行多列的数组中选取想要的数据，我们该怎么选。

建立一个多维数组供使用：

In [49]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**获取某行数据**

要获取某行数据，直接传入这行的位置，即第几行即可。例子如下所示。

In [50]:
# 获取第2行数据
arr[1]

array([4, 5, 6])

**获取某些行的数据**

要获取某些行的数据，直接传入这些行的位置区间即可

In [52]:
# 获取第2行和第3行的数据，包括第三行
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

同样也可以获取某行之前或之后的所有行的数据

In [53]:
# 获取第3行之前的所有行数据，不包括第3行
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

**获取某列数据**

要获取某列数据，直接在列位置处传入这个列的位置，即第几列即可。

In [54]:
# 获取第2列的数据
arr[:,1]

array([2, 5, 8])

上面代码中**逗号之前用来指明行位置，逗号之后用来指明列位置，当逗号之前是一个冒号时，表示获取所有的行**。

**获取某些列的数据**

要获取某些列的数据，直接在列位置处传入这些列的位置区间即可。

In [56]:
# 获取第1列到第3列的数据，不包括第3列
arr[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

同样也可以获取某列之前或之后的所有列数据

In [57]:
# 获取第3列之前的所有列，不包括第3列
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
# 获取第2列之后的所有列，包括第2列
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

**行列同时获取**

行列同时获取时，分别在行位置、列位置处指明要获取行、列的位置数。

In [62]:
# 获取第1到2行，第2到3列的数据
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

## 15.5 NumPy数组的数据预处理

### 15.5.1 NumPy数组的类型转换

在 NumPy 数组中转换数据类型用到的方法是`astype()`，在`astype`后的括号中指明要转换成的目标类型即可。

In [1]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

数组的原始数据类型为int32

In [2]:
arr.dtype

dtype('int32')

将arr数组从int类型转换为float类型

In [3]:
arr_float = arr.astype(np.float64)
arr_float

array([0., 1., 2., 3., 4.])

In [5]:
arr_float.dtype

dtype('float64')

将arr数据从int类型转换为str类型

In [7]:
arr_str = arr.astype(np.string_)
arr_str

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [8]:
arr_str.dtype

dtype('S11')

大家对这个方法可能比较熟悉，我们在5.4.2里面的Pandas部分也讲过，那这两个有何不同呢？这是两个库中的两个方法，但本质上是一样
的，**Pandas中的某一列其实就是NumPy数组**。

### 15.5.2 NumPy数组的缺失值处理

**缺失值处理分两步，第一步先判断是否含有缺失值，将缺失值找出来；第二步对缺失值进行填充**。

查找缺失值用到的方法是`isnan()`。在判断缺失值之前，先创建一个含有缺失值的数组，在NumPy中缺失值用`np.nan`表示。

In [9]:
# 创建一个含有缺失值的数组，nan表示缺失值
arr = np.array([1,2,np.NAN,4])
arr

array([ 1.,  2., nan,  4.])

创建含有缺失值的数组以后就可以用`isnan`方法对缺失进行判断了。**如果某一位置的值为缺失值，则该位置返回True，否则返回False**。

In [10]:
# 第三位为缺失值
np.isnan(arr)

array([False, False,  True, False])

找到缺失值以后就可以对缺失值进行填充，例如用0填充，方法如下:

In [12]:
arr[np.isnan(arr)] = 0
arr

array([1., 2., 0., 4.])

### 15.5.3 NumPy数组的重复值处理

重复值处理比较简单，直接调用`unique()`方法

In [13]:
arr = np.array([1,2,3,2,1])
np.unique(arr)

array([1, 2, 3])

## 15.6 NumPy数组重塑

所谓数组重塑就是更改数组的形状，比如将原来3行4列的数组重塑成4行3列的数组。在NumPy中用`reshape`方法来实现数组重塑。

### 15.6.1 一维数组重塑

一维数组重塑就是将数组从一行或一列数组重塑为多行多列的数组：

In [14]:
# 新建一个一维数组
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
# 将数组重塑为2行4列的多维数组
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
# 将数组重塑为4列2行的多维数组
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

上面的一维数组既可以转换为2行4列的多维数组，也可以转换为4行2列的多维数组。**无论是2行4列还是4行2列，只要重塑后数组中值的个数等于一维数组中值的个数即可**。

### 15.6.2 多维数组重塑

多维数组的重塑如下：

In [17]:
# 新建一个多维数组
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# 将数组重塑为4行3列的
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# 将数组重塑为2行6列的
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

我们同样可以将3行4列的多维数组重塑为4行3列或者2行6列的多维数组，只要**重塑后数组中值的个数等于重塑前数组中值的个数即可**。

### 15.6.3 数组转置

数组转置就是将数组的行旋转为列，用到的方法是`.T`，如下：

In [20]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 15.7 NumPy数组合并

### 15.7.1 横向合并

**横向合并就是将两个行数相等的数组在行方向上进行简单拼接**。与DataFrame合并不太一样，**NumPy 数组合并不需要公共列，只是将两个数组简单拼接在一起，有`concatenate`、`hstack`、`column_stack`三种方法可以实现**。

先新建两个数组，用来进行合并。

In [23]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

**`concatenate`方法**

`concatenate`方法中将两个待合并的数组以列表的形式传给`concatenate`方法，并通过设置axis参数来指明在行方向还是在列方向上进行合并。

In [24]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

参数axis = 1表示数组在行方向上进行合并。

**`hstack`方法**

**`hstack`方法直接将两个待合并数组以元组的形式传给hstack即可**，不需要设置axis参数。

In [25]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**`column_stack`方法**

`column_stack`方法与`hstack`方法基本一样，也是将两个待合并的数组以元组的形式传给`column_stack`即可。

In [26]:
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 15.7.2 纵向合并

横向合并是将两个行数相等的数组在行的方向上进行拼接，**纵向合并与横向合并类似，它将两个列数相等的数组在列的方向进行拼接，有
`concatenate`、`vstack`、`row_stack`三种方法可以实现**。

**`concatenate`方法**

使用`concatenate`方法对数组进行纵向合并时，参数axis的值必需为0。

In [27]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**`vstack`方法**

`vstack` 是与 `hstack` 相对应的方法，同样只要将待合并的数组以元组的形式传给vstack即可。

In [28]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**`row_stack`方法**

`row_stack` 是与 `column_stack` 相对应的方法，将两个待合并的数组以元组的形式传给`row_stack`即可达到数组纵向合并的目的。

In [29]:
np.row_stack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 15.8 常用数据分析函数

### 15.8.1 元素级函数

**元素级函数就是针对数组中的每个元素执行相同的函数操作**，主要函数及其说明如下表:
```text
函数                        说明
-------------------------------------------------------
abs                        求取每个元素的绝对值
sqrt                       求取每个元素的平方根
square                     求取每个元素的平方
exp                        计算各个元素以e为底的指数
log、log10、log2、log1p     分别计算以e为底，10为底，2为底的对数，以及log(1+x)
modf                       适用于浮点数，将小数和整数部分以独立的数组返回
isnan                      用来判断是否是NaN，返回一个布尔值
```
元素级函数的用法如下：

In [30]:
arr = np.arange(4)
np.square(arr)

array([0, 1, 4, 9], dtype=int32)

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

### 15.8.2 描述统计函数

描述统计函数是对整个  NumPy 数组或某条轴的数据进行统计运算，主要的函数及其说明如下表：
```text
函数                               说明
-------------------------------------------------------------------------
sum                               对数组中全部元素或某行/某列的元素求和
mean                              平均值求取
std、var                          分别为标准差、方差
min、max                          分别为最小值、最大值
argmin、argmax                    分别为最大值、最小值对应的索引
cumsum                            所有元素的累计和，结果以数组的形式返回
cumprod                           所有元素的累计积
```
新建一个数组代码如下：

In [32]:
# 新建一个数组
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

下面给出了几种常用的函数示例。

**求和**

依次对整个数组，数组中的每一行、每一列求和，代码如下：

In [33]:
# 对整个数组进行求和
arr.sum()

45

In [34]:
# 对数组的每一行分别求和
arr.sum(axis = 1)

array([ 6, 15, 24])

In [35]:
# 对数组的每一列求和
arr.sum(axis = 0)

array([12, 15, 18])

**求均值**

依次对整个数组，数组中的每一行、每一列求均值，代码如下：

In [36]:
# 对整个数组进行求平均值
arr.mean()

5.0

In [37]:
# 对行求平均值
arr.mean(axis = 1)

array([2., 5., 8.])

In [38]:
# 对列求平均值
arr.mean(axis = 0)

array([4., 5., 6.])

**求最值**

对整个数组求最大值，对数组中的每一行分别求最小值，对数组中的每一列分别求最大值。使用方法同上.

### 15.8.3 条件函数

Numpy 数组中的条件函数 `np.where(condition,x,y)`类似于 Excel 中的`if(condition,True,False)`函数，如果条件（condition）为真则返回x，如果条件为假则返回y。条件函数的例子如下:

In [40]:
# 新建一个数组用来存储学生成绩
arr = np.array([56, 61, 65])

np.where(arr > 60, '及格', '不及格')

array(['不及格', '及格', '及格'], dtype='<U3')

In [41]:
np.where(arr > 60)

(array([1, 2], dtype=int64),)

### 15.8.4 集合关系

每个数组都可以当作一个集合，**集合的关系其实就是两个数组之间的关系，主要有包含、交集、并集、差集四种**。

In [42]:
# 新建两个数组
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,5])

**包含**

判断数组arr1中包含数组arr2中的哪些值，如果包含则在对应位置返回True，否则返回False。

In [43]:
np.in1d(arr1,arr2)

array([ True,  True, False, False])

**交集**

交集就是返回两个数组中的公共部分

In [44]:
np.intersect1d(arr1,arr2)

array([1, 2])

**并集**

并集就是返回两个数组中含有所有数据元素的一个集合。

In [45]:
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5])

**差集**

差集就是返回在arr1数组中存在，但是在arr2数组中不存在的元素。

In [48]:
# 在arr1中存在，在arr2中不存在
np.setdiff1d(arr1,arr2)

array([3, 4])

In [50]:
# 在arr2中存在，在arr1中不存在
np.setdiff1d(arr2,arr1)

array([5])